### ISSUE TITLE
Visual/block editor: hitting enter twice does not create a new paragraph

### ISSUE THREAD

**Issue by barryhughes** [trendschau/typemill#435] opened 2024-01-06 15:32 UTC
The video tutorial found [in the Writers page of the docs](https://typemill.net/writers) notes that hitting enter twice will cause the block to be saved and that a new paragraph will automatically be opened below. In my testing with 2.0.3 in both Firefox and Opera, only the first of those things happens (the block is saved, but a new paragraph is not automatically opened).

![hit-enter-twice](https://github.com/typemill/typemill/assets/3594411/27f482a7-d285-4c69-b8f9-c803b0755cd8)

I'm a little unsure if the docs are current and this is a bug, or if it is a new feature of 2.0.3. If the latter, and what I'm seeing is expected, is there a keyboard shortcut that can be used to select what the next block should be?

I think opening a new paragraph automatically is probably what most people would want and expect, but it would also be kind of nifty if the content-type selector bar (I'm sure that's not the correct name, but adding a screenshot of the UI I'm referring to below 😄) received the focus and one could select the next content type using arrow keys and hitting space/enter.

![editor-selector-bar](https://github.com/typemill/typemill/assets/3594411/f0dbc508-d2e9-477a-89cc-c7eb7d8eff7e)

**Comment by trendschau** [comment] 2024-01-30 15:01
Sorry for late answer and thank you for the report. Yes, you are right, I will try to add this behavior again in the next release. New paragraph-block should open if you are at the end of the page.

**Comment by barryhughes** [comment] 2024-01-30 16:11
Great, thanks!

**Comment by trendschau** [comment] 2024-03-12 19:23
this has been added to version 2.2.2

**Comment by barryhughes** [comment] 2024-03-25 22:07
Thanks!

**Comment by UpstairsEmpire** [comment] 2024-11-19 16:29
I'm on 2.11 and this still is not working correctly for me. Hitting enter one closes the paragraph but hitting it a second time does not create a new one. @trendschau hoping you can take a look at this. Thank you!

**Comment by trendschau** [comment] 2024-11-20 07:33
Yes, sorry, it looks like this change got lost somewhere, I will check it and fix it for next release. I think this should be configurable in the writing section. Will take a look...

**Comment by trendschau** [comment] 2024-11-29 07:50
Ok, I tested it and it looks like this was already fixed in march and has been confirmed that it works. See screencast. 

Note, that this only works at the end of the article, it does not work if you insert new blocks somewhere in the middle of the page.

[Screencast-editor-hitting-twice.webm](https://github.com/user-attachments/assets/adcc3ea6-a983-4436-82c0-5a4de4bc558e)

**Closed as completed by trendschau** 2024-11-29 07:50 UTC
Labels: bug
