### ISSUE TITLE
Problem deleting a user

### ISSUE THREAD

**Issue by mkduew** [trendschau/typemill#462] opened 2024-03-25 11:15 UTC
after I delete a user as an admin, I get logged out. I should be remain logged in as an admin.

**Comment by trendschau** [comment] 2024-03-26 18:05
This should be fixed with version 2.3.3. Session should only stop if the user deletes his own account. Please check again, if it still does not work, please provide more details, I improved the code but could not reproduce this specific behavior.

**Closed as completed by trendschau** 2024-03-26 18:05 UTC
Labels: bug
