### ISSUE TITLE
Illegal character (_) in username

### ISSUE THREAD

**Issue by joho1968** [trendschau/typemill#482] opened 2024-06-12 07:20 UTC
Is there a particular reason an underscore (_) character is not allowed in usernames ... ? :thinking:

**Comment by trendschau** [comment] 2024-06-12 11:10
I have to check it in detail again, but in combination with the register plugin, underscore like (_unsername) is used to indicate registered but not yet confirmed users, so I would prefer to keep this limitation to avoid too many code-changes in different places. I also try to keep limitations as strict as possible to have a bit easier live with validations and thinking about security implications (which this probably does not have, I agree).

**Comment by trendschau** [comment] 2024-11-29 07:34
I will close this for now and keep it as it is for the reasons explained above.

**Closed as completed by trendschau** 2024-11-29 07:34 UTC
