### ISSUE TITLE
Issue with Backend and maybe Frontend – menu not fully displayed

### ISSUE THREAD

**Issue by aheinhold** [trendschau/typemill#479] opened 2024-05-18 19:35 UTC
Hi,

I started testing Typemill yesterday. I installed it on my web hosting package and created a user. I have encountered the following issue:
The backend is not fully displayed. Sometimes the sidebar menu appears, then it disappears, making Typemill unusable.
When the menu dissappears, the contend, e. g. forms are not visible and useable.

**Some screenshots**:
<img width="1181" alt="image" src="https://github.com/typemill/typemill/assets/45874736/b6ebefb3-9632-474e-8fee-7b8ab88edd16">

<img width="1180" alt="image" src="https://github.com/typemill/typemill/assets/45874736/821c62a2-0531-47da-8276-6bc8a553f623">

**Klick back to "System"**:

<img width="1174" alt="image" src="https://github.com/typemill/typemill/assets/45874736/02010c7f-4357-417c-8cd7-d530efb5928d">

**And to Content**:

<img width="1156" alt="image" src="https://github.com/typemill/typemill/assets/45874736/d1a107ad-cf3b-48c5-9d8e-12ebce4562af">

**Steps Taken to Resolve the Issue**:
I cleared the browser cache.
I used incognito mode.
I tested different browsers.

**Typemill Version**: 2.4.3
There are no error messages, and the Apache error log does not show any related errors.
My system runs on a shared web hosting package with [Hetzner](https://www.hetzner.com/de/webhosting/) (Level 4 Webhosting Package).
**PHP Version**: i tested 8.0-8.3

I would appreciate your assistance in resolving this issue.

Thank you in advance and best regards,
Alex

**Comment by trendschau** [comment] 2024-05-20 09:22
thank you for sharing! In the last screens the vue application does not run, but I cannot reproduce it (also running on hetzner). Very strange. Can you open the developer tools of your browser and check if there are errors in the console? See screenshot

![Screenshot from 2024-05-20 11-19-39](https://github.com/typemill/typemill/assets/2714547/e9f0b646-30d0-4f99-a584-765bd7214d44)

**Comment by aheinhold** [comment] 2024-05-21 04:44
If the contents of the "System" page are not displayed, I get the following errors

![image](https://github.com/typemill/typemill/assets/45874736/bdbaca6c-9e5b-4d9d-81d4-0362a2db26c1)

If the contents of the "Content" page are not displayed, I get the following errors

![image](https://github.com/typemill/typemill/assets/45874736/0b4f9dd6-7492-4c5e-ba99-ad59ee45d7a2)

Hopefully this helps...

**Comment by trendschau** [comment] 2024-05-22 09:31
I just see that the basic vue- apps are not defined but I don't see the reason and it is hard to bugfix from the distance. Maybe the vue library is not loaded correctly. You could try it again with a fresh Installation of Version 2.5.0. I also use hetzner and it should not be a problem.

**Comment by aheinhold** [comment] 2024-05-22 11:26
As suggested, I freshly installed version 2.5.0.
The first time I called I received the following information:
<img width="527" alt="image" src="https://github.com/typemill/typemill/assets/45874736/c490780d-5e7d-41bc-972e-d9e813887a36">

I created the directories, set the permissions and then set up my user.
Still, I encounter the same behavior as before.

<img width="547" alt="image" src="https://github.com/typemill/typemill/assets/45874736/a549464b-8576-4e42-86d7-9a87201dadc5">

<img width="553" alt="image" src="https://github.com/typemill/typemill/assets/45874736/b653e930-d5ee-44c1-a162-1abc6b241783">

**Comment by trendschau** [comment] 2024-05-23 07:28
I tested it again on my local machines (xampp windows and linux) and I could not reproduce this, on hetzner it also works without errors. The errors of the system check are not really relevant. Can you check if there are any errors in the network tab and if all ressources are loaded? Do you have any special environment like a proxy or something similar?

Since I did not get any similar error reports from other users, I guess it is something with the environment, browser settings or similar, but hard to guess from the distance.

**Comment by trendschau** [comment] 2024-11-29 07:38
ok, sorry that I could not help here. I guess it is something with the environment since it works for me and other users. I will close it for now.

**Closed as completed by trendschau** 2024-11-29 07:38 UTC
